import { Platform } from 'react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system/legacy';

type ReceiptDevice = {
  id: string;
  model: string;
  storage: string;
  imei: string;
  imei2?: string;
  pta: string;
  status: string;
  cost: number;
  repair: number;
  tax: number;
  sale?: number;
  date: string;
};

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function money(n: number): string {
  return 'Rs ' + Math.round(n).toLocaleString('en-PK');
}

function receiptHtml(device: ReceiptDevice): string {
  const total = device.cost + device.repair + device.tax;
  const profit = device.sale != null ? device.sale - total : null;
  const isSold = device.status === 'Sold' && device.sale != null;
  return `<!doctype html><html><head><meta charset="utf-8"><style>
    body{font-family:-apple-system,Helvetica,Arial,sans-serif;color:#14141F;padding:32px;}
    h1{color:#6945D9;margin:0;font-size:26px;}
    .sub{color:#8A879B;margin-top:2px;font-size:13px;}
    table{width:100%;border-collapse:collapse;margin-top:24px;font-size:14px;}
    td{padding:8px 0;border-bottom:1px solid #EEEDF4;}
    td.k{color:#8A879B;}
    td.v{text-align:right;font-weight:600;}
    .total td{font-weight:800;font-size:16px;border-bottom:none;padding-top:14px;}
    .profit{margin-top:20px;background:#F0EBFC;border-radius:10px;padding:14px 18px;font-size:16px;color:#4C339E;font-weight:700;}
    .foot{margin-top:40px;color:#B1AEC0;font-size:11px;}
  </style></head><body>
    <h1>flipwise.</h1>
    <div class="sub">${isSold ? 'Sale Receipt' : 'Device Summary'} &middot; ${esc(device.id)}</div>
    <table>
      <tr><td class="k">Model</td><td class="v">${esc(device.model)}</td></tr>
      <tr><td class="k">Storage</td><td class="v">${esc(device.storage)}</td></tr>
      <tr><td class="k">IMEI</td><td class="v">${esc(device.imei)}</td></tr>
      ${device.imei2 ? `<tr><td class="k">IMEI 2</td><td class="v">${esc(device.imei2)}</td></tr>` : ''}
      <tr><td class="k">PTA status</td><td class="v">${esc(device.pta)}</td></tr>
      <tr><td class="k">Acquired</td><td class="v">${esc(device.date)}</td></tr>
    </table>
    <table>
      <tr><td class="k">Purchase price</td><td class="v">${money(device.cost)}</td></tr>
      <tr><td class="k">Repairs &amp; parts</td><td class="v">${money(device.repair)}</td></tr>
      <tr><td class="k">PTA tax</td><td class="v">${money(device.tax)}</td></tr>
      <tr class="total"><td>Total invested</td><td class="v">${money(total)}</td></tr>
      ${isSold ? `<tr class="total"><td>Sale price</td><td class="v">${money(device.sale as number)}</td></tr>` : ''}
    </table>
    ${profit != null ? `<div class="profit">Profit on sale: ${money(profit)}</div>` : ''}
    <div class="foot">Generated by Flipwise on ${new Date().toLocaleDateString()}</div>
  </body></html>`;
}

export async function shareDeviceReceipt(device: ReceiptDevice): Promise<void> {
  const html = receiptHtml(device);
  if (Platform.OS === 'web') {
    await Print.printAsync({ html });
    return;
  }
  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: `${device.model} receipt` });
  }
}

function toCsvValue(v: string | number): string {
  const s = String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export function buildInventoryCsv(devices: ReceiptDevice[]): string {
  const header = ['Device ID', 'Model', 'Storage', 'IMEI', 'PTA Status', 'Status', 'Purchase Price', 'Repair Cost', 'PTA Tax', 'Sale Price', 'Profit', 'Acquisition Date'];
  const rows = devices.map((d) => {
    const total = d.cost + d.repair + d.tax;
    const profit = d.sale != null ? d.sale - total : '';
    return [d.id, d.model, d.storage, d.imei, d.pta, d.status, d.cost, d.repair, d.tax, d.sale ?? '', profit, d.date].map(toCsvValue).join(',');
  });
  return [header.join(','), ...rows].join('\n');
}

export async function exportInventoryCsv(devices: ReceiptDevice[]): Promise<void> {
  const csv = buildInventoryCsv(devices);
  const filename = `flipwise-inventory-${new Date().toISOString().slice(0, 10)}.csv`;
  if (Platform.OS === 'web') {
    const doc = (globalThis as any).document;
    const blob = new (globalThis as any).Blob([csv], { type: 'text/csv' });
    const url = (globalThis as any).URL.createObjectURL(blob);
    const a = doc.createElement('a');
    a.href = url;
    a.download = filename;
    doc.body.appendChild(a);
    a.click();
    a.remove();
    (globalThis as any).URL.revokeObjectURL(url);
    return;
  }
  const uri = FileSystem.cacheDirectory + filename;
  await FileSystem.writeAsStringAsync(uri, csv, { encoding: FileSystem.EncodingType.UTF8 });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'text/csv', dialogTitle: 'Export inventory' });
  }
}
